// lib/dummyData.ts (tambahkan di bawah data yang sudah ada)

export const dummyContents = [
  {
    id: '1',
    thumbnail: '/dummy/thumb1.jpg',
    caption: '5 Tips meningkatkan engagement Instagram di tahun 2024 🚀',
    date: '12 Jan 2024',
    likes: 1240,
    comments: 87,
    sentiment: { type: 'positive' as const, score: 82 },
  },
  {
    id: '2',
    thumbnail: '/dummy/thumb2.jpg',
    caption: 'Behind the scene photoshoot produk terbaru kami! 📸',
    date: '10 Jan 2024',
    likes: 890,
    comments: 45,
    sentiment: { type: 'positive' as const, score: 75 },
  },
  {
    id: '3',
    thumbnail: '/dummy/thumb3.jpg',
    caption: 'Tutorial singkat: Cara menggunakan fitur baru aplikasi kami',
    date: '8 Jan 2024',
    likes: 2100,
    comments: 132,
    sentiment: { type: 'positive' as const, score: 91 },
  },
  {
    id: '4',
    thumbnail: '/dummy/thumb4.jpg',
    caption: 'Update maintenance server minggu ini. Mohon maaf atas ketidaknyamanannya.',
    date: '5 Jan 2024',
    likes: 320,
    comments: 67,
    sentiment: { type: 'neutral' as const, score: 48 },
  },
  {
    id: '5',
    thumbnail: '/dummy/thumb5.jpg',
    caption: 'Giveaway akhir tahun! Ada hadiah menarik untuk 3 pemenang 🎁',
    date: '1 Jan 2024',
    likes: 3500,
    comments: 520,
    sentiment: { type: 'positive' as const, score: 88 },
  },
  {
    id: '6',
    thumbnail: '/dummy/thumb6.jpg',
    caption: 'Pertanyaan: Fitur apa yang paling sering kamu gunakan?',
    date: '28 Des 2023',
    likes: 670,
    comments: 98,
    sentiment: { type: 'positive' as const, score: 68 },
  },
  {
    id: '7',
    thumbnail: '/dummy/thumb7.jpg',
    caption: 'Pengumuman perubahan harga langganan mulai Januari 2024',
    date: '20 Des 2023',
    likes: 450,
    comments: 210,
    sentiment: { type: 'negative' as const, score: 32 },
  },
  {
    id: '8',
    thumbnail: '/dummy/thumb8.jpg',
    caption: 'Selamat Tahun Baru 2024! Semoga tahun ini penuh berkah 🎉',
    date: '31 Des 2023',
    likes: 2800,
    comments: 340,
    sentiment: { type: 'positive' as const, score: 94 },
  },
];